"""Initial schema from final models.py

Revision ID: 6f1eef4d87c9
Revises: 
Create Date: 2025-09-18 23:19:54.519317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1eef4d87c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nav_update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_date')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('is_family_member', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registrar', sa.Enum('CAMS', 'Karvy', name='registrar_types'), nullable=True),
    sa.Column('fund_url', sa.String(length=255), nullable=True),
    sa.Column('latest_nav', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fund_house', sa.String(length=255), nullable=True),
    sa.Column('isin_growth', sa.String(length=20), nullable=True),
    sa.Column('isin_div_payout', sa.String(length=20), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin_div_payout'),
    sa.UniqueConstraint('isin_growth')
    )
    op.create_index('ix_fund_isin_div_payout', 'fund', ['isin_div_payout'], unique=False)
    op.create_index('ix_fund_isin_growth', 'fund', ['isin_growth'], unique=False)
    op.create_table('fund_nav_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('nav_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("nav_type = 'growth'", name='chk_nav_type_growth_only'),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'nav_date', 'isin', name='uq_fund_nav_date_isin')
    )
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('units', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('folio_number', sa.String(length=50), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('registrar', sa.Enum('CAMS', 'Karvy', name='registrar_types'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment')
    op.drop_table('fund_nav_history')
    op.drop_index('ix_fund_isin_growth', table_name='fund')
    op.drop_index('ix_fund_isin_div_payout', table_name='fund')
    op.drop_table('fund')
    op.drop_table('user')
    op.drop_table('sub_category')
    op.drop_table('nav_update_log')
    op.drop_table('family')
    op.drop_table('category')
    # ### end Alembic commands ###
