"""Sync schema after manual ISIN rename

Revision ID: bcb17ef00f03
Revises: 6f1eef4d87c9
Create Date: 2025-09-23 00:14:30.226767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb17ef00f03'
down_revision: Union[str, Sequence[str], None] = '6f1eef4d87c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
