"""Add password_hash to User

Revision ID: 165f77aec1c6
Revises: 123456789abc
Create Date: 2025-12-25 20:17:14.563550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '165f77aec1c6'
down_revision = '123456789abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('isin_scheme_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('isin'))

    op.drop_table('isin_scheme_map')
    with op.batch_alter_table('investment_history', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('investment_history', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))

    op.create_table('isin_scheme_map',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isin', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('scheme_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('scheme_name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('isin_scheme_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('isin'), ['isin'], unique=True)

    # ### end Alembic commands ###
