"""Add staging investment table

Revision ID: 16fab3986c64
Revises: 65e185b681e9
Create Date: 2026-01-15 12:21:27.248924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fab3986c64'
down_revision = '65e185b681e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_snapshot_date'), type_='unique')
        batch_op.create_unique_constraint('uq_user_snapshot_date', ['user_id', 'snapshot_date', 'dashboard_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_snapshot_date', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_snapshot_date'), ['user_id', 'snapshot_date'])

    op.drop_table('staging_investment')
    # ### end Alembic commands ###
