"""add folio_number to StagingInvestment

Revision ID: 500378f88dab
Revises: 16fab3986c64
Create Date: 2026-08-16 17:55:24.740939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500378f88dab'
down_revision = '16fab3986c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staging_investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folio_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staging_investment', schema=None) as batch_op:
        batch_op.drop_column('folio_number')

    # ### end Alembic commands ###
