"""Add family_id + family constraints to PortfolioSnapshot

Revision ID: 65e185b681e9
Revises: 5b30f055a273
Create Date: 2026-01-07 20:19:50.344336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65e185b681e9'
down_revision = '5b30f055a273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('portfolio_value',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index('ix_family_snapshot_lookup', ['family_id', 'snapshot_date'], unique=False)
        batch_op.create_index('ix_user_snapshot_lookup', ['user_id', 'snapshot_date'], unique=False)
        batch_op.create_unique_constraint('uq_family_snapshot_date', ['family_id', 'snapshot_date', 'dashboard_type'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_family_snapshot_date', type_='unique')
        batch_op.drop_index('ix_user_snapshot_lookup')
        batch_op.drop_index('ix_family_snapshot_lookup')
        batch_op.drop_constraint('uq_user_snapshot_date', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_snapshot_date'), ['user_id', 'snapshot_date'])
        batch_op.create_index(batch_op.f('ix_snapshot_lookup'), ['user_id', 'snapshot_date'], unique=False)
        batch_op.alter_column('portfolio_value',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=18, scale=2),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
