"""Add DeletionLog table

Revision ID: c7c7bff2841c
Revises: 74406e5d393f
Create Date: 2025-10-06 00:18:35.403650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7c7bff2841c'
down_revision = '74406e5d393f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isin_scheme_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('scheme_code', sa.String(length=20), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('deletion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registrar', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('isin_lookup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isin_lookup',
    sa.Column('isin', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fund_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('isin'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('deletion_log')
    op.drop_table('isin_scheme_map')
    # ### end Alembic commands ###
