"""add portfolio_snapshot table

Revision ID: ec8357f9d1c6
Revises: cb8dd0d3acc4
Create Date: 2026-01-04 11:38:22.062638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec8357f9d1c6'
down_revision = 'cb8dd0d3acc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_user_snapshot_date')
    )
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_lookup', ['user_id', 'snapshot_date'], unique=False)

    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.alter_column('is_matured',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.alter_column('is_matured',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_lookup')

    op.drop_table('portfolio_snapshot')
    # ### end Alembic commands ###
